//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KwikCEDICT.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KwikCEDICT.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;td width=&quot;22%&quot; class=&quot;MakeRight&quot;&gt;Simplified:&lt;/td&gt;
        ///		&lt;td width=&quot;78%&quot;&gt;&lt;a class=&quot;TextChinese&quot;&gt;{0}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td class=&quot;MakeRight&quot;&gt;Traditional:&lt;/td&gt;
        ///		&lt;td&gt;&lt;a class=&quot;TextChinese&quot;&gt;{1}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td class=&quot;MakeRight&quot;&gt;Pinyin:&lt;/td&gt;
        ///		&lt;td&gt;{2}&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td class=&quot;MakeRight&quot;&gt;English:&lt;/td&gt;
        ///		&lt;td&gt;{3}&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string htmlBody {
            get {
                return ResourceManager.GetString("htmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;head&gt;
        ///	&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot;&gt;
        ///	&lt;title&gt;Kwik CEDICT&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///	body {
        ///		font-family: Tahoma, Geneva, sans-serif;
        ///		font-size: 20pt;
        ///	}
        ///	table {
        ///    	border-collapse: collapse;
        ///	}
        ///	.MakeRight {
        ///		text-align: right;
        ///		vertical-align: top;
        ///	}
        ///	.TextChinese {
        ///		font-family: &quot;Adobe Kaiti Std R&quot;;
        ///	}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;.
        /// </summary>
        internal static string htmlHead {
            get {
                return ResourceManager.GetString("htmlHead", resourceCulture);
            }
        }
    }
}
